[
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 23,
    "title": "Blue Tanktop",
    "img": "https://i.ibb.co/7CQVJNm/blue-tank.png",
    "price": 25,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 24,
    "title": "Floral Blouse",
    "img": "https://i.ibb.co/4W2DGKm/floral-blouse.png",
    "price": 20,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 25,
    "title": "Floral Dress",
    "img": "https://i.ibb.co/KV18Ysr/floral-skirt.png",
    "price": 80,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 26,
    "title": "Red Dots Dress",
    "img": "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
    "price": 80,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 27,
    "title": "Striped Sweater",
    "img": "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    "price": 45,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 28,
    "title": "Yellow Track Suit",
    "img": "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
    "price": 135,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 29,
    "title": "White Blouse",
    "img": "https://i.ibb.co/qBcrsJg/white-vest.png",
    "price": 20,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 30,
    "title": "Camo Down Vest",
    "img": "https://i.ibb.co/xJS0T3Y/camo-vest.png",
    "price": 325,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 31,
    "title": "Floral T-shirt",
    "img": "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
    "price": 20,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 32,
    "title": "Black & White Longsleeve",
    "img": "https://i.ibb.co/55z32tw/long-sleeve.png",
    "price": 25,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 33,
    "title": "Pink T-shirt",
    "img": "https://i.ibb.co/RvwnBL8/pink-shirt.png",
    "price": 25,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 34,
    "title": "Jean Long Sleeve",
    "img": "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
    "price": 40,
  },
  {
    "desc":"The best peice of clothing out there.lorem isdum sgghdj  fg hd hdmnfunhjgffgjgjg;fflf",
    "category":"clothing",
    "color":"red",
    "size":"L",
    "availableQty":3,
    "slug": 35,
    "title": "Burgundy T-shirt",
    "img": "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
    "price": 25,
  },
];
