import Head from "next/head";
import Image from "next/image";
import Homeitem from "../components/Homepage/Homeitem";
import { useContext } from "react";
import cartContext from "../context/cartContext";
import { getCookie } from "cookies-next";
import { useEffect } from "react";
import { useState } from "react";
export default function Home() {
  const context = useContext(cartContext);

  return (
    <>
      <Head>
        <title>Charizard-Your personal shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-2">
        <img className="w-[150vw]" src={"/bg.jpg"} alt="nopw" />
      </div>

      <Homeitem />
    </>
  );
}
