import Head from "next/head";

import Homeitem from "../components/Homepage/Homeitem";
import product from "../models/product";
import connectMongo from "../middleware/connectTomongo";

export default function Home() {
  // console.log(products);
  return (
    <>
      <Head>
        <title>Charizard-Your personal shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-2">
        <img className="w-[150vw]" src={"/bg.jpg"} alt="nopw" />
      </div>

      <Homeitem />
    </>
  );
}
export async function getServerSideProps(context) {
  connectMongo();
  let products = await product.find({ category: "shirts" });
  console.log(products);

  // let product = await fetch("http://localhost:3000/api/getProducts/shirts");
  // let data = await product.json();
  return {
    props: { products: JSON.parse(JSON.stringify(products)) }, // will be passed to the page component as props
  };
}
